name: Build

on:
  push:
    branches-ignore:
      - 'master' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: "0"
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: set-up
      run: |
        npm install -g typescript
        npm install -g lerna
    - name: action-lerna
      uses: m19c/action-lerna@1.0.0
      run: |
        lerna exec -- npm install
        lerna bootstrap --hoist
    - name: build
      run: npm run build